// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostgreEFCorePerfTest.Database;

#nullable disable

namespace PostgreEFCorePerfTest.Migrations
{
    [DbContext(typeof(SampleContext))]
    [Migration("20220204141003_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PostgreEFCorePerfTest.Database.Entities.SampleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Data1")
                        .HasColumnType("text");

                    b.Property<string>("Data2")
                        .HasColumnType("text");

                    b.Property<string>("Data3")
                        .HasColumnType("text");

                    b.Property<string>("Data4")
                        .HasColumnType("text");

                    b.Property<string>("Data5")
                        .HasColumnType("text");

                    b.Property<string>("Data6")
                        .HasColumnType("text");

                    b.Property<string>("Data7")
                        .HasColumnType("text");

                    b.Property<string>("Data8")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Samples");
                });
#pragma warning restore 612, 618
        }
    }
}
